# Generated by Django 3.2.7 on 2022-11-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='sadegh', max_length=225),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='sadegh', max_length=225),
        ),
    ]
