# Generated by Django 3.2.7 on 2022-11-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='post',
            field=models.CharField(max_length=225),
        ),
    ]
