# Generated by Django 3.2.7 on 2022-12-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20221218_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='brand',
        ),
    ]
