# Generated by Django 3.2.7 on 2022-12-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_productspecification_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='name')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='brandType', to='store.producttype')),
            ],
            options={
                'verbose_name': 'product Brand',
                'verbose_name_plural': 'product Brand',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='store.brand'),
        ),
    ]
