# Generated by Django 3.2.7 on 2022-12-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
