# Generated by Django 3.2.7 on 2023-03-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_comment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='images/', verbose_name='slider1')),
                ('image_2', models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='images/', verbose_name='slider2')),
                ('image_3', models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='images/', verbose_name='slider3')),
            ],
        ),
    ]
