# Generated by Django 3.2.7 on 2023-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20230407_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('در حال پرداخت', 'Pending'), ('پرداخت شده', 'Complete'), ('پرداخت نشده', 'Failed')], default='پرداخت نشده', max_length=13),
        ),
    ]
